# AppAdminPassword = "example-password"
# PrivateSubnetName = "terraform-azure-demo-vnet-private-subnet"
# PublicSubnetName = "terraform-azure-demo-vnet-public-subnet"
# ResourceGroupName = "azure-ixnetwork-1-app-2-agents"
# VnetName = "terraform-azure-demo-vnet-vnet"